name: proyecto
recipe: lamp
proxy:
  dbms:
    - dbms-proyecto.lndo.site
config:
  webroot: .
services:
  dbms:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    config:
      php: php.ini
